#!/usr/bin/env python3
"""Assemble docs/kart_spec/*.md into docs/KART_SPEC.md.

Issue #190's deliverable is one document, but it is written by several agents at
once and a single file would have them fighting over it. So the sections are the
editable source, one file per assembly, and this concatenates them in name order.

    tools/spec/assemble.py            # write docs/KART_SPEC.md
    tools/spec/assemble.py --check    # non-zero if the assembled file is stale

`--check` exists because a generated file with no way to prove it matches its
source is a file that silently rots. It is cheap enough to run beside the other
gates.
"""

from __future__ import annotations

import glob
import os
import sys

BANNER = (
    "<!-- GENERATED by tools/spec/assemble.py from docs/kart_spec/*.md.\n"
    "     Edit the section files, not this one. Re-run the tool after editing. -->\n"
)


def sections(root: str) -> list[str]:
    # Name order, not glob order: glob's order is filesystem-dependent and this
    # file is compared byte-for-byte by --check.
    return sorted(glob.glob(os.path.join(root, "docs", "kart_spec", "*.md")))


def assembled(root: str) -> str:
    parts = [BANNER]
    for path in sections(root):
        text = open(path, encoding="utf-8").read().rstrip("\n")
        parts.append("\n" + text + "\n")
    return "".join(parts)


def main() -> int:
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    found = sections(root)
    if not found:
        print("error: no sections under docs/kart_spec/", file=sys.stderr)
        return 1

    target = os.path.join(root, "docs", "KART_SPEC.md")
    text = assembled(root)

    if "--check" in sys.argv[1:]:
        current = open(target, encoding="utf-8").read() if os.path.exists(target) else ""
        if current != text:
            print(
                "error: docs/KART_SPEC.md is stale against docs/kart_spec/ "
                "(%d section file(s)); run tools/spec/assemble.py" % len(found),
                file=sys.stderr,
            )
            return 1
        print("    spec     %d section(s), docs/KART_SPEC.md up to date" % len(found))
        return 0

    with open(target, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(
        "    spec     %d section(s) -> docs/KART_SPEC.md (%d lines)"
        % (len(found), text.count("\n"))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
