class_name KartRig
extends RefCounted

## Builds a driveable kart into a scene: mesh, chassis collider, driver, audio.
##
## ## Why this exists, and what it is an apology for
##
## `proving_ground.gd` and `test_track.gd` each carry about 140 lines of identical
## kart plumbing — load the generated `.glb`, find the four wheel pivots, size one
## box collider from the mesh minus the wheels, attach a `PlayerDriver`, attach the
## three audio emitters and the listener. `src/vehicle/kart_body.h` says why the
## node does not own any of it: it is asset plumbing rather than physics, and a C++
## node that loads a gitignored `.glb` cannot be instantiated in a test.
##
## Two copies were a deliberate trade — CLAUDE.md records it — because two scenes
## doing it two different ways would be two karts. **Three copies is not that
## trade, it is the bug the trade was guarding against**, so the third caller
## extracted it instead of pasting it. `scenes/game/valdirone.tscn` is that caller.
##
## Issue #183 finished the job: `proving_ground.gd` and `test_track.gd` now build
## through this class too, so there is one copy and not three. That was deliberately
## a separate commit from the extraction, because `proving_ground.tscn` is where
## every §6.4 figure is measured — moving its spawn plumbing in the same commit as
## the extraction would have been a change to the instrument and a change to the
## thing being measured at once. The migration's whole proof is that `drive.sh`'s
## four state hashes did not move.
##
## What this class does **not** own, because all three callers wanted it in a
## different place or a different order: the assists (`AssistSettings.apply`, which
## has to be able to see the scene's own arguments), the `PhysicsDraw` overlay, the
## tuning registry, and the respawn quiet tick — `test_track.gd`'s respawn also has
## to tell a `SessionRunner`, and `proving_ground.gd` has no runner to tell.

## Where the kart mesh comes from. Gitignored and regenerated by
## `tools/blender/genkart.sh`, so it is loaded at run time rather than referenced
## from a `.tscn` — a hard `ext_resource` would make the scene fail to load on a
## fresh clone.
const KART_MESH_PATH := "res://assets/generated/kart.glb"

## The four wheel pivots the generated mesh exposes, in the order the body reports
## its own wheels: front left, front right, rear left, rear right.
const WHEEL_PIVOT_NAMES: PackedStringArray = [
	"wheel_fl", "wheel_fr", "wheel_rl", "wheel_rr",
]

## Ride height at spawn, meters above the road surface.
##
## `proving_ground.gd`'s number and its reason: placing the kart at exactly wheel
## height means the first tick starts with the tires already interpenetrating, and
## Jolt resolves that by pushing them apart. A kart that hops on spawn is this, not
## a suspension bug.
const SPAWN_LIFT := 0.12

## Everything the caller gets back, so a scene holds one object rather than seven
## loose references it has to keep in step.
var kart: KartBody
var driver: PlayerDriver
var wheel_pivots: Array[Node3D] = []
var wheel_rest_yaw := PackedFloat32Array()
var engine_voice: Object
var scrub_voice: Object
var wind_voice: Object


## Build the kart at a transform and parent it under `parent`.
##
## `spawn` is the body transform, already lifted — the caller owns where the road
## is and this class does not know what a track is.
func build(parent: Node3D, spawn: Transform3D, args: Dictionary) -> KartBody:
	kart = KartBody.new()
	kart.name = "Kart"
	# Set before `add_child`, because `KartBody::_ready` captures its spawn from
	# whatever transform it finds if nobody has told it one.
	kart.transform = spawn
	kart.set_spawn(spawn)

	var visual := _load_mesh(kart)
	if visual != null:
		var pivots := _wheel_pivots_of(visual)
		if pivots.size() == WHEEL_PIVOT_NAMES.size():
			wheel_pivots = pivots
			for pivot in pivots:
				wheel_rest_yaw.append(pivot.rotation.y)
			_build_collision(kart, visual, pivots)
		else:
			push_error(
				"kart mesh has %d of the %d wheel pivots (wheel_fl/fr/rl/rr) — "
				% [pivots.size(), WHEEL_PIVOT_NAMES.size()]
				+ "run tools/blender/genkart.sh"
			)
	parent.add_child(kart)

	# The driver. ADR-0040: the body is handed its input rather than fetching it, so
	# a scene without this node is a kart nobody can drive.
	driver = PlayerDriver.new()
	driver.name = "Driver"
	parent.add_child(driver)
	driver.kart_path = driver.get_path_to(kart)

	# The engine note, at the engine. Null under every headless gate, which have no
	# audio device and must not need one — see `engine_voice_rig.gd`.
	engine_voice = EngineVoiceRig.attach(kart)
	# Tire scrub and wind, issue #84. Three emitters, because the three are not in
	# the same place: the note at the engine mount, the scrub at the rear axle, and
	# the wind at the driver's head and not in the world at all.
	var noise: Array = EngineVoiceRig.attach_noise(kart)
	scrub_voice = noise[0]
	wind_voice = noise[1]
	# The listener, at the driver's head. Issue #160: without it Godot falls back to
	# whichever `Camera3D` is current, which was measured to swing the level 20.7 dB
	# as the chase camera moves — so the mix changed every time somebody pressed V,
	# and only one of the two mixes was ever judged.
	EngineVoiceRig.attach_listener(kart)

	# Scripted input, for stills and for anything with no keyboard. Held constant for
	# the whole run, so the same command produces the same still. A valid
	# `input_driver` Callable **overrides** the pushed input, per ADR-0040.
	if args.has("throttle") or args.has("steer") or args.has("brake"):
		var throttle := Cmdline.as_float(args, "throttle", 0.0)
		var brake := Cmdline.as_float(args, "brake", 0.0)
		var steer := Cmdline.as_float(args, "steer", 0.0)
		kart.input_driver = func() -> Dictionary:
			return {"throttle": throttle, "brake": brake, "steer": steer}

	return kart


## Turn the front wheel meshes to the angle the solver is steering at.
##
## The angle comes out of `wheel_report()` per corner rather than from the steering
## input, so what is drawn is `steering.h`'s Ackermann output — the two front wheels
## are at *different* angles in a corner, and that is visible.
##
## Wheel **spin** is not animated, because nothing publishes a per-wheel angle: the
## solid rear axle has one speed for two wheels (issue #33) and the fronts have none
## at all. Faking it from road speed would be a second, invisible model of something
## the solver already owns, which is the mistake ADR-0031 records.
##
## This read the wrong keys from #183 until the migration measured it. The
## extraction wrote `wheel.get("steer")` and `wheel.get("spin")`; `wheel_report()`
## publishes neither — the steer angle is `steer_angle` and there is no spin field
## anywhere in `src/`. Both `get`s took their `0.0` default on every corner of every
## tick, so on `valdirone.tscn` the front wheels sat dead straight through every
## corner while the solver steered underneath them, and `rotation.x` was pinned to
## zero rather than left where the mesh shipped it. `kart_body.cpp` warns about
## exactly this shape a few lines above the Dictionary it fills: "the panel reads
## every key with a default, so a renamed key does not fail loudly, it draws a zero
## forever." The two scenes this class was extracted *from* both read `steer_angle`
## and never wrote `rotation.x`, so the bug arrived in the extraction itself.
func update_wheel_visuals() -> void:
	if kart == null:
		return
	update_wheel_visuals_from(kart.wheel_report())


## The same, for a caller that already has this tick's `wheel_report()`.
##
## `test_track.gd` needs the report anyway to build its surface read-out, and
## `wheel_report()` allocates an Array of four Dictionaries every call.
## `driving_hud.gd`'s header makes the argument in its own words: an allocation is
## fine for a panel that samples while it is open and wrong for an overlay that
## draws every frame. So the caller that has one passes it rather than causing a
## second.
func update_wheel_visuals_from(report: Array) -> void:
	if wheel_pivots.size() != WHEEL_PIVOT_NAMES.size():
		return
	for index in mini(report.size(), wheel_pivots.size()):
		var wheel: Dictionary = report[index]
		wheel_pivots[index].rotation.y = (
			wheel_rest_yaw[index] + float(wheel["steer_angle"])
		)


func _load_mesh(body: Node3D) -> Node3D:
	if not ResourceLoader.exists(KART_MESH_PATH):
		push_error("no kart at %s — run tools/blender/genkart.sh" % KART_MESH_PATH)
		return null
	var instance := (load(KART_MESH_PATH) as PackedScene).instantiate() as Node3D
	instance.name = "KartMesh"
	body.add_child(instance)
	return instance


func _wheel_pivots_of(root: Node3D) -> Array[Node3D]:
	var found: Array[Node3D] = []
	for wheel_name in WHEEL_PIVOT_NAMES:
		var node := root.find_child(wheel_name, true, false) as Node3D
		if node != null:
			found.append(node)
	return found


## A single box for the chassis, sized from the mesh minus the wheels.
##
## `proving_ground.gd`'s, unchanged, including the two reasons the wheels are
## excluded: a collider over a tire fights its own suspension ray, and a box that
## reached the road would have Jolt supplying a second normal force on top of the
## suspension's.
func _build_collision(body: Node3D, visual: Node3D, pivots: Array[Node3D]) -> void:
	var bounds := _visual_bounds(visual, pivots)
	var shape := BoxShape3D.new()
	# The underside sits at the bottom of the frame rails rather than at the lowest
	# thing on the kart, so a curb strike catches the frame and not an invisible
	# skirt. The curb height is bracketed against this number.
	var floor_y := 0.035
	var top := bounds.position.y + bounds.size.y
	shape.size = Vector3(bounds.size.x, maxf(top - floor_y, 0.05), bounds.size.z)

	var collider := CollisionShape3D.new()
	collider.shape = shape
	collider.position = Vector3(
		bounds.get_center().x, floor_y + shape.size.y * 0.5, bounds.get_center().z
	)
	collider.name = "ChassisShape"
	body.add_child(collider)


func _visual_bounds(root: Node3D, excluded: Array[Node3D]) -> AABB:
	var bounds := AABB()
	var started := false
	for node in _descendants(root):
		var visual := node as VisualInstance3D
		if visual == null or visual.get_aabb().size == Vector3.ZERO:
			continue
		var skip := false
		for pivot in excluded:
			if visual.is_ancestor_of(pivot) or pivot.is_ancestor_of(visual):
				skip = true
				break
		if skip:
			continue
		var world := (root.transform * _relative_transform(root, visual)) * visual.get_aabb()
		if not started:
			bounds = world
			started = true
		else:
			bounds = bounds.merge(world)
	return bounds


func _relative_transform(root: Node3D, node: Node3D) -> Transform3D:
	var accumulated := Transform3D()
	var walker := node
	while walker != null and walker != root:
		accumulated = walker.transform * accumulated
		walker = walker.get_parent() as Node3D
	return accumulated


func _descendants(node: Node) -> Array[Node]:
	var found: Array[Node] = []
	for child in node.get_children():
		found.append(child)
		found.append_array(_descendants(child))
	return found
