class_name KartDebugVehicle
extends VehicleBody3D

## ROADMAP M3a's throwaway kart: Godot's built-in `VehicleBody3D` driving the M2
## mesh, purely to prove the integration boundary.
##
## **This is scheduled for deletion.** ARCHITECTURE.md §6 says `VehicleBody3D` is
## explicitly not used — its raycast model is too coarse for kart feel, it has no
## concept of a solid rear axle, and the chassis-flex and jacking terms that make
## a kart a kart cannot be expressed through it. M3b replaces the whole file with
## the C++ solver. What it exists to answer *now* is the question ARCHITECTURE.md
## §19 names as the least-charted part of the plan: whether a force-based vehicle,
## Godot's `_physics_process`, and Jolt's stepping agree with each other. Until
## something drives, that question is unanswerable and everything downstream —
## cameras, track, telemetry — has nothing to sit on.
##
## Two rules it does keep, because they outlive it:
##
##   1. **No dimension is restated here.** Wheel positions, radii and the wheel
##      base come out of the generated mesh's own pivot nodes, the same way
##      `scripts/look/kartview.gd` reads the manifest rather than hardcoding the
##      wheelbase. A kart regenerated with a different track width drives on the
##      new one without an edit here.
##   2. **Nothing reads wall-clock time.** ARCHITECTURE.md §8 rule 1. The drive
##      model is a pure function of input and physics state, so the determinism
##      harness has something meaningful to hash even at this stage.

## Where the kart mesh comes from. Gitignored and regenerated by
## `tools/blender/genkart.sh`, so it is loaded at run time rather than referenced
## from a `.tscn` — a hard `ext_resource` would make the scene fail to load on a
## fresh clone.
const KART_MESH_PATH := "res://assets/generated/kart.glb"

## CIK class minimum, driver included. ARCHITECTURE.md §6.
const MASS_WITH_DRIVER := 175.0

## Fraction of the wheelbase the center of mass sits behind the midpoint.
## ARCHITECTURE.md §6 asks for "slightly rearward" — a KZ carries its engine
## outboard and behind the driver's hip, and the real figure is about 55/45 rear.
const CG_REARWARD_FRACTION := 0.05

## Steering lock, radians. 25 degrees is the figure the bodywork clearance tables
## in issues #109 and #110 were measured at, so using anything else here would
## make the fairing's measured tire clearance describe a kart that does not exist.
const STEER_LOCK := deg_to_rad(25.0)

## How fast the wheels reach full lock, radians per second. A kart's steering is
## direct — no rack, no assistance, a short arm on the kingpin — so this is fast
## enough to feel unfiltered but not instant, which would make a keyboard's
## step input unusable.
const STEER_RATE := 3.4

## Lock is scaled down with speed so a keyboard tap at 130 km/h does not spin the
## kart. This is a driver-aid stand-in, not physics; the real thing at M3b is
## Ackermann geometry plus caster jacking, where high-speed stability is emergent.
const STEER_SPEED_FALLOFF := 0.55

## Peak crank power, watts. 45 hp, the low end of ARCHITECTURE.md §6.3's range.
const ENGINE_POWER := 33_500.0

## Traction force ceiling, newtons, total at the contact patch. It only binds
## below 12.6 m/s, where 33.5 kW cannot deliver this much anyway; above that the
## power curve is the limit and raising this changes nothing. 2,650 N is 1.55 g
## at 175 kg — a hard launch on warm slicks with most of the mass over the driven
## axle. The real ceiling is the friction circle, and this model has no tire model
## to ask, which is the gap M3b closes.
const TRACTION_LIMIT := 2_650.0

## Aerodynamic drag as a single lumped coefficient, so that F_drag = DRAG * v^2.
## 0.36 is 0.5 * rho * CdA with CdA = 0.6, which is where a kart with an upright
## driver sits — most of the frontal area is the human.
##
## It was 0.57 first, solved backwards from the top speed, and that was wrong in
## an instructive way. 33.5 kW against a realistic CdA tops out near 163 km/h,
## not the 140 km/h §6.4 quotes, so making the top speed come out of drag alone
## meant claiming a CdA of 0.95 — and then paying for it in acceleration, which
## dropped 0-100 outside its band. **A real KZ is limited by its gearing, not by
## its drag**: it runs out of revs in sixth. So the drag stays honest and the
## top speed is imposed separately, by `TOP_SPEED` below.
const DRAG := 0.36

## Where the drive cuts out, m/s. 38.9 m/s is 140 km/h, the middle of §6.4's
## range, and it stands in for the rev limiter in top gear — the thing that
## actually stops a KZ. Tapered rather than switched, over `TOP_SPEED_TAPER`,
## because §6.3 asks for a soft cut approaching the limiter and because a hard
## step in force at 140 km/h would be visible as a jolt.
const TOP_SPEED := 38.9
const TOP_SPEED_TAPER := 1.5

## Two-stroke engine braking, as drag proportional to speed when the throttle is
## shut. §6.3 calls this heavy enough to shape corner entry, and leaving it out
## is what makes a kart feel like it is coasting on ice.
const ENGINE_BRAKE := 26.0

## Brake force at full pedal, newtons, total across the wheels in contact.
##
## 2,900 N was the first value — 1.7 g at 175 kg, the middle of §6.4's 1.5-2.0 g
## band — and it measured 2.23 g, because the brakes are not the only thing
## slowing the kart: drag and the two-stroke engine braking below are both
## working at the same time, and together they are worth another half a g at
## 25 m/s. Set from the measurement instead, which is the only way the number
## means what its band says.
const BRAKE_FORCE := 2_150.0

## Suspension travel, meters. A kart has no suspension at all — the frame flexes
## instead — but `VehicleWheel3D` raycasts from its origin down through
## `wheel_rest_length` plus this, so zero travel means a wheel that never reports
## contact. 20 mm is the smallest value that still finds the ground on the first
## tick, and the stiffness below makes it behave as if it were not there.
const SUSPENSION_TRAVEL := 0.02
const SUSPENSION_REST_LENGTH := 0.02
const SUSPENSION_STIFFNESS := 250.0
const SUSPENSION_MAX_FORCE := 12_000.0

## Grip, in `VehicleWheel3D`'s own units, which are not a friction coefficient.
## Rear higher than front because a kart's rear tires are wider (215 mm against
## 135 mm) and warmer. Tuned against the measured skidpad, not derived — the
## derived version is M3b's Pacejka fit.
##
## The first values were 4.2 and 5.4, and the kart **rolled over** on the
## skidpad: it pulled 3.3 g, and its own geometry tips at
## (rear track / 2) / (center of mass height) = 0.59 / 0.25 = 2.37 g. A kart that
## grips harder than it can stand up to does not slide, it flips — which is a
## real behavior at the margin and not one to sit in the middle of. These land
## the sustained figure inside §6.4's 2.0-2.5 g band, below the tipping point.
const FRICTION_FRONT := 2.7
const FRICTION_REAR := 3.4

## How much of the chassis roll the wheel loads follow. A kart is torsionally
## stiff and rolls very little, so this is well below the 1.0 a car would use.
const ROLL_INFLUENCE := 0.25

## Publicly readable state, for the HUD and the telemetry that lands at M3b.
var speed_ms := 0.0
var steer_input := 0.0
var throttle_input := 0.0
var brake_input := 0.0
var wheels_on_ground := 0

var _wheels: Array[VehicleWheel3D] = []

## Rear wheel radius, meters, read from the mesh. Used to convert the newtons
## every constant in this file is written in into the wheel torque
## `VehicleBody3D` actually wants.
var _drive_radius := 0.1475
var _visual: Node3D
var _spawn := Transform3D()


func _ready() -> void:
	mass = MASS_WITH_DRIVER
	# Jolt lets a body sleep, and a kart sitting on the grid with no input is
	# exactly the case it would sleep in. It then ignores the first frame of
	# throttle. Sleeping is a rendering-scale optimization the sim does not want.
	can_sleep = false
	continuous_cd = true

	# Godot's project defaults apply `linear_damp = 0.1` and `angular_damp = 0.1`
	# to every rigid body. That is a velocity-proportional force nobody in this
	# project asked for: at 10 m/s it is a full 1 m/s^2, about a quarter of the
	# kart's acceleration at that speed, and it was silently eating the difference
	# between this model's predicted 0-100 time and its measured one.
	#
	# Replaced rather than reduced. ARCHITECTURE.md §6 gives aerodynamics one line
	# — light drag, negligible downforce — and this file implements it explicitly
	# in `DRAG`, where the number is derived from a top speed and can be argued
	# with. Two drag models, one of them invisible, is how a solver ends up tuned
	# against a constant nobody knows is there.
	linear_damp_mode = RigidBody3D.DAMP_MODE_REPLACE
	linear_damp = 0.0
	angular_damp_mode = RigidBody3D.DAMP_MODE_REPLACE
	angular_damp = 0.0

	_visual = _load_mesh()
	if _visual == null:
		return

	var pivots := _wheel_pivots(_visual)
	if pivots.size() != 4:
		push_error(
			"kart mesh has %d wheel pivots, expected 4 (wheel_fl/fr/rl/rr) — "
			% pivots.size() + "run tools/blender/genkart.sh"
		)
		return

	_build_collision(_visual, pivots)
	_build_wheels(pivots)
	_place_center_of_mass(pivots)
	_spawn = global_transform


# --- construction ----------------------------------------------------------


func _load_mesh() -> Node3D:
	if not ResourceLoader.exists(KART_MESH_PATH):
		push_error(
			"no kart at %s — run tools/blender/genkart.sh" % KART_MESH_PATH
		)
		return null
	var instance := (load(KART_MESH_PATH) as PackedScene).instantiate() as Node3D
	instance.name = "KartMesh"
	add_child(instance)
	return instance


## The four wheel pivots the Blender modules publish, keyed by name.
##
## `kartlib` registers these as an interface on purpose — `BuildContext.publish`'s
## docstring says the name is the contract and the vehicle solver looks them up by
## it. Measured rather than assumed: each pivot sits at its wheel's true center,
## which is not obvious from the parameter block, because `track_front` and
## `track_rear` describe the kart's *outside* width and the centerline track is
## one tire width narrower (1.105 m front, 1.185 m rear).
func _wheel_pivots(root: Node3D) -> Dictionary:
	var found := {}
	for wheel_name: String in ["wheel_fl", "wheel_fr", "wheel_rl", "wheel_rr"]:
		var node := root.find_child(wheel_name, true, false) as Node3D
		if node != null:
			found[wheel_name] = node
	return found


## Wheel radius from the wheel's own mesh, not from the parameter block.
##
## The tire's outer diameter is what touches the road, and it is the tire mesh's
## Y extent — which already includes `tire_sidewall_bulge` and the shoulder
## radius. Reading `tire_front_diameter` instead would be right today and wrong
## the moment a tire profile parameter changes.
func _wheel_radius(pivot: Node3D) -> float:
	var bounds := AABB()
	var started := false
	for child in pivot.get_children():
		var visual := child as VisualInstance3D
		if visual == null:
			continue
		var local := visual.transform * visual.get_aabb()
		if not started:
			bounds = local
			started = true
		else:
			bounds = bounds.merge(local)
	if not started:
		return 0.14
	return bounds.size.y * 0.5


## A single box for the chassis, sized from the mesh minus the wheels.
##
## Deliberately crude and deliberately *not* the frame tubes: at M3a the body
## collider only has to keep the kart off the ground when it lands, and a convex
## hull of 37,856 triangles would make every measurement in this milestone a
## measurement of collision cost. Real per-part collision arrives with the track
## in M5, where there is something to collide with other than a plane.
##
## The wheels are excluded because they are raycast wheels — a collider over a
## tire would fight its own suspension ray and the kart would sit on its box
## instead of its tires.
func _build_collision(visual: Node3D, pivots: Dictionary) -> void:
	var bounds := _visual_bounds(visual, pivots.values())
	var shape := BoxShape3D.new()
	# Trimmed to the ground clearance the frame is built to: the box's underside
	# sits at the bottom of the frame rails rather than at the lowest thing on the
	# kart, so a curb strike catches the frame and not an invisible skirt.
	var floor_y := 0.035
	var top := bounds.position.y + bounds.size.y
	shape.size = Vector3(bounds.size.x, maxf(top - floor_y, 0.05), bounds.size.z)

	var collider := CollisionShape3D.new()
	collider.shape = shape
	collider.position = Vector3(
		bounds.get_center().x, floor_y + shape.size.y * 0.5, bounds.get_center().z
	)
	collider.name = "ChassisShape"
	add_child(collider)


func _visual_bounds(root: Node3D, excluded: Array) -> AABB:
	var bounds := AABB()
	var started := false
	for node in _descendants(root):
		var visual := node as VisualInstance3D
		if visual == null or visual.get_aabb().size == Vector3.ZERO:
			continue
		var skip := false
		for pivot: Node3D in excluded:
			if visual.is_ancestor_of(pivot) or pivot.is_ancestor_of(visual):
				skip = true
				break
		if skip:
			continue
		var world := (root.transform * _relative_transform(root, visual)) * visual.get_aabb()
		if not started:
			bounds = world
			started = true
		else:
			bounds = bounds.merge(world)
	return bounds


func _relative_transform(root: Node3D, node: Node3D) -> Transform3D:
	var accumulated := Transform3D()
	var walker := node
	while walker != null and walker != root:
		accumulated = walker.transform * accumulated
		walker = walker.get_parent() as Node3D
	return accumulated


## One `VehicleWheel3D` per pivot, with the wheel's own visual reparented onto it.
##
## Reparenting is what makes the picture honest: the wheel node steers and spins,
## so a wheel that is not turning on screen is a wheel that is not turning in the
## sim. Leaving the visuals under the mesh would have hidden a locked wheel behind
## a body that still moved.
func _build_wheels(pivots: Dictionary) -> void:
	for wheel_name: String in ["wheel_fl", "wheel_fr", "wheel_rl", "wheel_rr"]:
		var pivot: Node3D = pivots[wheel_name]
		var is_front := wheel_name.begins_with("wheel_f")
		var radius := _wheel_radius(pivot)

		var wheel := VehicleWheel3D.new()
		wheel.name = wheel_name.to_upper()
		wheel.wheel_radius = radius
		wheel.wheel_rest_length = SUSPENSION_REST_LENGTH
		wheel.suspension_travel = SUSPENSION_TRAVEL
		wheel.suspension_stiffness = SUSPENSION_STIFFNESS
		wheel.suspension_max_force = SUSPENSION_MAX_FORCE
		wheel.damping_compression = 4.0
		wheel.damping_relaxation = 4.4
		wheel.wheel_friction_slip = FRICTION_REAR if not is_front else FRICTION_FRONT
		wheel.wheel_roll_influence = ROLL_INFLUENCE
		wheel.use_as_steering = is_front
		# Solid rear axle, no differential (ARCHITECTURE.md §6). `VehicleBody3D`
		# has no axle concept, so both rear wheels simply get the same drive
		# force — which is the half of the behavior it can express. The half it
		# cannot, that a locked axle scrubs unless the inside rear lifts, is the
		# reason M3b exists.
		wheel.use_as_traction = not is_front
		# The wheel hangs `wheel_rest_length` below its node, so the node goes
		# that far above the wheel center the mesh reported.
		wheel.position = pivot.position + Vector3.UP * SUSPENSION_REST_LENGTH
		if not is_front:
			_drive_radius = radius
		add_child(wheel)

		pivot.reparent(wheel, false)
		pivot.position = Vector3.ZERO
		pivot.rotation = Vector3.ZERO
		_wheels.append(wheel)


## Center of mass placed between the axles, biased rearward.
##
## `RigidBody3D` defaults to the origin of the body, and the kart mesh's origin is
## on the ground between the front wheels' axle line — so leaving it alone would
## put the mass at road level ahead of where it belongs and the kart would refuse
## to rotate. Height matters more than the bias does: it is what weight transfer
## is levered against, and ARCHITECTURE.md §6 forbids faking that with a bias
## term, so it has to be geometrically right.
func _place_center_of_mass(pivots: Dictionary) -> void:
	var front: Node3D = pivots["wheel_fl"]
	var rear: Node3D = pivots["wheel_rl"]
	var mid_z := (front.position.z + rear.position.z) * 0.5
	var wheelbase := absf(rear.position.z - front.position.z)
	center_of_mass_mode = RigidBody3D.CENTER_OF_MASS_MODE_CUSTOM
	# Height from the two masses rather than picked: an 80 kg kart carries its
	# frame, engine and tires low, around 0.12 m, and a 95 kg driver reclined in
	# the seat sits at about 0.32 m, so the pair land at 0.23 m. It matters more
	# than it looks: the ratio of half the rear track to this height is the
	# lateral g at which the kart tips instead of sliding — 0.5925 / 0.23 = 2.58 g
	# — and the first version, at 0.25 m, put that threshold at 2.37 g, below the
	# 2.0-2.5 g §6.4 asks the kart to sustain. The kart rolled over on the skidpad
	# rather than reaching its own cornering figure.
	center_of_mass = Vector3(0.0, 0.23, mid_z + wheelbase * CG_REARWARD_FRACTION)


func _descendants(node: Node) -> Array[Node]:
	var found: Array[Node] = []
	for child in node.get_children():
		found.append(child)
		found.append_array(_descendants(child))
	return found


# --- driving ---------------------------------------------------------------


func _physics_process(delta: float) -> void:
	_read_input(delta)

	var velocity := linear_velocity
	speed_ms = velocity.length()
	# Signed along the kart's own forward axis, so reversing and spinning are not
	# reported as forward motion. Godot's forward is -Z.
	var forward := -global_transform.basis.z
	var forward_speed := velocity.dot(forward)

	for wheel: VehicleWheel3D in _wheels:
		if wheel.use_as_steering:
			wheel.steering = steer_input * _steer_lock()

	_apply_drive(forward, forward_speed, delta)
	_apply_longitudinal_resistance(forward, forward_speed)

	wheels_on_ground = 0
	for wheel: VehicleWheel3D in _wheels:
		if wheel.is_in_contact():
			wheels_on_ground += 1

	if Input.is_action_just_pressed(&"respawn"):
		respawn()


## Whether the kart reads the input map at all.
##
## Turned off while the debug flight camera is current, because that camera reuses
## the drive keys. The body keeps simulating either way — pausing it instead would
## mean the thing being inspected is not the thing that was running.
var _input_enabled := true

## An alternative source of driver input, called once per physics tick and
## expected to return `{throttle, brake, steer}` with each in its usual range.
##
## This is how a scripted scenario drives: `tools/verify/drive_probe.gd` supplies
## a function of the tick number and gets a run that is a pure function of it,
## which is what makes the resulting state hash comparable between processes. It
## is also the shape M6's replay needs — a replay is an input stream, and an
## input stream is exactly this callable reading from an array instead of from a
## keyboard. Live input is the special case, not the general one.
var input_driver := Callable()


func set_process_input_enabled(enabled: bool) -> void:
	_input_enabled = enabled


func _read_input(delta: float) -> void:
	if input_driver.is_valid():
		var scripted: Dictionary = input_driver.call()
		throttle_input = clampf(float(scripted.get("throttle", 0.0)), 0.0, 1.0)
		brake_input = clampf(float(scripted.get("brake", 0.0)), 0.0, 1.0)
		# Rate-limited on the same terms as a human's input, so a scripted run and
		# a driven one are the same experiment. A scenario that wants an instant
		# step has to ask for it over several ticks, which is also true of a driver.
		steer_input = move_toward(
			steer_input, clampf(float(scripted.get("steer", 0.0)), -1.0, 1.0), STEER_RATE * delta
		)
		return
	if not _input_enabled:
		throttle_input = 0.0
		brake_input = 0.0
		steer_input = move_toward(steer_input, 0.0, STEER_RATE * delta)
		return
	throttle_input = Input.get_action_strength(&"throttle")
	brake_input = Input.get_action_strength(&"brake")
	var target := Input.get_action_strength(&"steer_left") - Input.get_action_strength(&"steer_right")
	# Rate-limited rather than applied directly, so a keyboard's instant 0-to-1
	# does not step the front wheels to full lock inside one tick. A stick that
	# moves slower than the limit is unaffected.
	steer_input = move_toward(steer_input, target, STEER_RATE * delta)


## Lock available at the current speed. See `STEER_SPEED_FALLOFF`.
func _steer_lock() -> float:
	var normalized := clampf(speed_ms / 30.0, 0.0, 1.0)
	return STEER_LOCK * (1.0 - STEER_SPEED_FALLOFF * normalized)


## Drive force at the contact patch, newtons, total.
##
## Power-limited above the speed where 33.5 kW stops being able to deliver
## `TRACTION_LIMIT`, traction-limited below it. This is a stand-in for §6.3's
## torque curve through six gears: it has the right asymptote and none of the
## shape, so it pulls at 3,000 rpm in a way a real KZ absolutely does not.
func _traction(forward_speed: float) -> float:
	if throttle_input <= 0.0:
		return 0.0
	var available := ENGINE_POWER / maxf(absf(forward_speed), ENGINE_POWER / TRACTION_LIMIT)
	var limiter := clampf((TOP_SPEED - forward_speed) / TOP_SPEED_TAPER, 0.0, 1.0)
	return throttle_input * minf(available, TRACTION_LIMIT) * limiter


## Drive and braking, applied as forces at the tire contact patches.
##
## ## Why not `engine_force` and `brake`
##
## `VehicleBody3D` has both properties and neither is in newtons. Measured, not
## assumed: at one fixed throttle the kart settled at a speed implying about 3.1x
## the force the model had asked for, and at another it implied 0.2x — the
## property is a wheel torque that then goes through the wheel's own friction
## solver, so there is no single conversion factor to write down. Calibrating a
## number that changes with speed is how a model ends up with a constant nobody
## can justify.
##
## So the drive force is applied directly, in newtons, and `engine_force` and
## `brake` stay at zero. Three things follow, and all three are improvements:
##
##   * every constant in this file is now a real quantity that can be checked
##     against ARCHITECTURE.md §6.4 by hand;
##   * the force is applied **at the contact patch**, not at the center of mass,
##     so squat under power and dive under braking come out of the geometry
##     instead of being absent;
##   * it is the same shape M3b's solver uses — per-wheel forces on a Jolt body
##     from `_physics_process` — so this milestone proves the integration that
##     one depends on rather than proving `VehicleBody3D`'s.
##
## What it gives up is longitudinal tire slip: the wheel model no longer limits
## drive force, so this kart cannot spin its wheels. `TRACTION_LIMIT` is standing
## in for a friction circle until there is a tire model to ask, which is exactly
## the gap M3b closes.
func _apply_drive(forward: Vector3, forward_speed: float, delta: float) -> void:
	var driven: Array[VehicleWheel3D] = []
	for wheel: VehicleWheel3D in _wheels:
		if wheel.use_as_traction and wheel.is_in_contact():
			driven.append(wheel)

	# A kart with its driven wheels in the air has no drive. That is the correct
	# behavior and it is also the one that makes the inside-rear lift in
	# ARCHITECTURE.md §6 visible: with a locked axle both rear wheels leave
	# together on this model, so the kart coasts through the moment.
	if not driven.is_empty():
		var share := _traction(forward_speed) / float(driven.size())
		for wheel: VehicleWheel3D in driven:
			_force_at_contact(wheel, forward * share)

	if brake_input <= 0.0:
		return
	var braking: Array[VehicleWheel3D] = []
	for wheel: VehicleWheel3D in _wheels:
		if wheel.is_in_contact():
			braking.append(wheel)
	if braking.is_empty():
		return
	# Clamped so one tick of braking cannot reverse the kart's direction of
	# travel. Without this, a full brake at walking pace applies more impulse than
	# the kart's remaining momentum and it snaps into reverse — an artifact of the
	# fixed timestep, not a behavior anyone asked for.
	var stopping := minf(brake_input * BRAKE_FORCE, absf(forward_speed) * mass / delta)
	var direction := forward * -signf(forward_speed)
	var share := stopping / float(braking.size())
	for wheel: VehicleWheel3D in braking:
		_force_at_contact(wheel, direction * share)


## Apply a force at a wheel's contact patch.
##
## `apply_force`'s offset is measured from the **body's origin**, in global
## coordinates — not from the center of mass. This file said the opposite for a
## milestone, CLAUDE.md's trap list said the opposite, and so did ADR-0031.
## `tools/verify/contact_probe.gd` settles it: with the center of mass moved to
## (0, 0.5, 0) and the offset passed as exactly zero, the body picks up
## 0.3788 rad/s where a center-of-mass convention predicts zero, and that matches
## the body-origin prediction to 1.2e-7. Godot's own documentation agrees in one
## sentence — "position is the offset from the body origin in global
## coordinates" — which is the part nobody read.
##
## Passing `contact - to_global(center_of_mass)` therefore applied the force at
## `origin + contact - com`, which is a torque of
## `(contact - com) x F  +  (origin - com) x F`. The second term is not small and
## it is not random: the kart mesh's origin sits on the ground and so does every
## contact patch, so those two arms have the *same* vertical component, and the
## pitch and roll moments from any tire force came out **exactly doubled** for
## any center-of-mass height. Measured on this kart's geometry: 5.079 rad/s of
## pitch per tick where 2.540 was intended, a ratio of 1.99996. Yaw was worse
## rather than merely doubled — the longitudinal arms differ in sign, so a
## lateral force produced a yaw moment that should not exist at all.
##
## The contact point is reconstructed from the wheel node and its radius for the
## same reason `PhysicsDraw` does it: `VehicleWheel3D` does not publish one.
func _force_at_contact(wheel: VehicleWheel3D, force: Vector3) -> void:
	var contact := wheel.global_position + Vector3.DOWN * wheel.wheel_radius
	apply_force(force, contact - global_position)


## Drag and engine braking, applied as a force at the center of mass.
##
## Both act against the direction of travel along the kart's own axis rather than
## against the world velocity: a kart sliding sideways is not being slowed by its
## engine, and applying either to the full velocity vector would damp a slide into
## submission and hide exactly the behavior M3b is built to produce.
func _apply_longitudinal_resistance(forward: Vector3, forward_speed: float) -> void:
	var magnitude := DRAG * forward_speed * forward_speed
	if throttle_input <= 0.0:
		magnitude += ENGINE_BRAKE * absf(forward_speed)
	apply_central_force(forward * -signf(forward_speed) * magnitude)


## Put the kart back where it started, stopped and upright.
##
## Velocities are zeroed as well as the transform. Teleporting a body with its
## momentum intact leaves it moving at 40 m/s inside whatever it was respawned
## next to, and Jolt resolves that by launching it.
func respawn() -> void:
	global_transform = _spawn
	linear_velocity = Vector3.ZERO
	angular_velocity = Vector3.ZERO
	steer_input = 0.0


func set_spawn(transform: Transform3D) -> void:
	_spawn = transform
	global_transform = transform


## Per-wheel state, for the debug draw and the HUD. One dictionary per wheel in
## fl, fr, rl, rr order.
func wheel_report() -> Array[Dictionary]:
	var report: Array[Dictionary] = []
	for wheel: VehicleWheel3D in _wheels:
		report.append({
			"name": wheel.name,
			"contact": wheel.is_in_contact(),
			"skid": wheel.get_skidinfo(),
			"rpm": wheel.get_rpm(),
			"steering": wheel.steering,
			"origin": wheel.global_position,
			"radius": wheel.wheel_radius,
			"travel": wheel.wheel_rest_length + wheel.suspension_travel,
		})
	return report
