#ifndef KART_CORE_RACE_RULES_H
#define KART_CORE_RACE_RULES_H

#include "core/session.h"

#include <cmath>

// The race format, as arithmetic. ROADMAP M3c, ADR-0043.
//
// Nothing in src/core/ may include godot-cpp. See docs/DECISIONS.md ADR-0017.
// This header is also allocation-free and locale-free for the reasons `tuning.h`
// gives: fixed-size arrays, no `std::vector`, no `std::string`, and the one sort
// in the file is hand-rolled because `std::stable_sort` allocates.
//
// ## Why this is a header in src/core/ and not a GDScript file
//
// A classification is a list of driver ids and results. Ordering one, adding up
// points and deciding what runs next is arithmetic over plain structs, so it goes
// where the tire model and the gearbox already live: compiled with one include
// path, tested by `tests/run.sh` in seconds with no engine, no scene and no
// setting. GDScript is left with what only GDScript can do — load a scene, draw a
// table, move a focus ring.
//
// ## The failure this file exists to prevent
//
// `docs/GAMEDESIGN.md` §4 puts **four** points scales in a single race weekend and
// three of them begin with 50 or 25. `docs/REFERENCES.md` says the sharp thing
// about that: collapse any pair and the standings look entirely plausible and are
// simply wrong, forever, **because there is no render to disagree with it.** A
// wrong tire curve produces a kart that drives badly and somebody notices in ten
// minutes. A wrong points scale produces a championship table nobody ever checks.
//
// So `tests/core/test_race_rules.cpp` asserts the four scales are pairwise
// distinct. It is a strange-looking test and it is the highest-value one in the
// module, because the defect it catches is a copy-paste that compiles, runs, and
// produces a table.
//
// ## Two rules here are OURS, not the FIA's, and they are marked in place
//
//   1. Truncating a 36-place scale to 8 places — see `POINTS_SCALE_PLACES`.
//   2. Promotion at top 3 — that one lives in `standings.h`.
//
// Everything else carries an article number from `docs/REFERENCES.md`'s G-series
// documents, in the style `kz_reference.h` uses: the citation sits beside the
// number, because a scale with no provenance is indistinguishable from a scale
// somebody adjusted for feel.
//
// Citation keys, from `docs/REFERENCES.md` "Race format and sporting regulations":
//
//   G1  FIA Karting General Prescriptions, 2026
//   G2  FIA Karting Specific Prescriptions, 2026
//   G4  FIA Karting European Championship - OK, Sporting Regulations, 2026
//
// And one rule from G4 Art. 1 governs the reading of all of them: the French text
// is authoritative and the English column is what everyone reads. Where the two
// could differ, the value here is the one both columns agree on.

namespace kart::core {

// The sanity ceiling on any classification, taken from `session.h` rather than
// restated. `SESSION_MAX_ENTRIES` is 34 and its comment explains why: roughly a
// full FIA grid, chosen so a parser that produced garbage can be rejected.
//
// **The design's field size of 8 is data and is not a constant anywhere in this
// file.** ADR-0046 is explicit that slot count is data, and `GAMEDESIGN.md` §6
// derives the eight from an audio measurement that is expected to move. Every
// function below takes the field it is given.
inline constexpr int RULES_MAX_ENTRIES = SESSION_MAX_ENTRIES;

// No driver. Used by every lookup that can fail, so a missing driver is a value
// rather than an out-of-range index.
inline constexpr int DRIVER_NONE = -1;

// --- the four scales ----------------------------------------------------------
//
// **Truncated to 8 places, and the truncation is OURS.** G2's scales run to 36th
// place. The rejected alternative was rescaling the real values to spread across
// an 8-kart field, and it was rejected because real numbers exist and inventing a
// spread throws them away: 50-44-41-38 is a shape somebody argued about, and any
// 8-place respacing of it is a shape nobody did.
//
// The consequence is that a field larger than this scores zero below 8th, which is
// wrong rather than merely compressed. `points_scale_covers()` exists so that a
// caller can detect it instead of discovering it in a standings table. The
// remaining real values are recorded in `docs/REFERENCES.md` and extending an
// array here is the whole fix.
inline constexpr int POINTS_SCALE_PLACES = 8;

// Qualifying Heat position points. G2 Art. 18 C. Orders the Super Heat grid.
// Full scale: 50, 44, 41, 38, 36, 34, 32, 30, 28, 27, 26 ... 1 (36th).
//
// Note 44 -> 41 -> 38: a 3-point gap and then a run of 2s. That kink is why this
// scale cannot be confused with any of the other three by shape alone, and it is
// also why it must not be regenerated by a formula.
inline constexpr int HEAT_POSITION_POINTS[POINTS_SCALE_PLACES] = {
	50, 44, 41, 38, 36, 34, 32, 30
};

// Super Heat position points. G2 Art. 18 D. Orders the Final grid.
// Full scale: 90, 80, 72, 66, 60, 54, 50, 46, 42, 38, 34, 32 ... 1 (36th).
//
// The only scale of the four that does not start at 50 or 25, and therefore the
// only one a collapse could not hide in.
inline constexpr int SUPER_HEAT_POSITION_POINTS[POINTS_SCALE_PLACES] = {
	90, 80, 72, 66, 60, 54, 50, 46
};

// Championship points from the intermediate classification after the heats, and
// from the Super Heat classification. G2 Art. 19.
// Full scale: 25, 22, 19, 17, 15, 13, 11, 9, 7, 6, 5, 4, 3, 2, 1 (15th).
inline constexpr int CHAMPIONSHIP_HEAT_POINTS[POINTS_SCALE_PLACES] = {
	25, 22, 19, 17, 15, 13, 11, 9
};

// Championship points from the Final. G2 Art. 19.
// Full scale: 50, 44, 38, 34, 30, 26, 22, 18, 14, 10, 8, 6, 4, 2, 1 (15th).
//
// **This scale is exactly twice `CHAMPIONSHIP_HEAT_POINTS`, place for place, for
// every place an 8-kart field has.** 50/25, 44/22, 38/19, 34/17, 30/15, 26/13,
// 22/11, 18/9 — all exactly 2. The two scales only diverge at 10th place, where
// the Final pays 10 against the heats' 6 and the ratio breaks.
//
// That is a real property of G2 Art. 19 and it is a trap twice over. It means a
// `2 * CHAMPIONSHIP_HEAT_POINTS` implementation would pass every test an 8-kart
// field can write; and it means a **half-credit Final result awards exactly the
// same total as a full-credit heat result** (see `DistanceCredit`), so a
// championship total cannot be decomposed back into positions. `standings.h`
// stores the Final position explicitly for that reason rather than deriving it.
// `test_race_rules.cpp` pins both facts so that neither is rediscovered.
inline constexpr int CHAMPIONSHIP_FINAL_POINTS[POINTS_SCALE_PLACES] = {
	50, 44, 38, 34, 30, 26, 22, 18
};

// One championship point for the fastest lap of the Final. G2 Art. 19.
// `GAMEDESIGN.md` §4 keeps it, and it is the only points award in the weekend
// that is not a function of a finishing position.
inline constexpr int FINAL_FASTEST_LAP_POINT = 1;

enum class PointsScale : int {
	HeatPosition = 0,
	SuperHeatPosition = 1,
	ChampionshipHeat = 2,
	ChampionshipFinal = 3,
};

inline constexpr int POINTS_SCALE_COUNT = 4;

inline const char *points_scale_name(PointsScale scale) {
	switch (scale) {
		case PointsScale::HeatPosition: return "heat_position";
		case PointsScale::SuperHeatPosition: return "super_heat_position";
		case PointsScale::ChampionshipHeat: return "championship_heat";
		case PointsScale::ChampionshipFinal: return "championship_final";
	}
	return "invalid";
}

inline const int *points_scale_values(PointsScale scale) {
	switch (scale) {
		case PointsScale::HeatPosition: return HEAT_POSITION_POINTS;
		case PointsScale::SuperHeatPosition: return SUPER_HEAT_POSITION_POINTS;
		case PointsScale::ChampionshipHeat: return CHAMPIONSHIP_HEAT_POINTS;
		case PointsScale::ChampionshipFinal: return CHAMPIONSHIP_FINAL_POINTS;
	}
	return nullptr;
}

// Points for a 1-based finishing position on one scale. Total: position 0 is "not
// classified" and scores nothing, and a position past the truncated scale scores
// nothing rather than reading off the end of the array.
inline int points_for(PointsScale scale, int position) {
	const int *values = points_scale_values(scale);
	if (values == nullptr || position < 1 || position > POINTS_SCALE_PLACES) {
		return 0;
	}
	return values[position - 1];
}

// Whether the truncated scales actually cover a field of this size.
//
// This is the guard on the decision above. `GAMEDESIGN.md` §6 sets the field from
// an audio measurement and says so; the day that measurement allows ten karts, the
// scales stop covering the field and every driver from 9th back scores zero. A
// caller that checks this gets told; a caller that does not gets a plausible table.
inline bool points_scale_covers(int entry_count) {
	return entry_count <= POINTS_SCALE_PLACES;
}

// --- half points --------------------------------------------------------------
//
// Championship points are carried as **integer halves**, because the
// part-distance rule below awards half points and half of 25 is not an integer.
//
// The alternative is a double, and doubles would in fact be exact here — every
// value is a multiple of 0.5 and those are exactly representable. Integers are
// used anyway for the reason `tuning.h` uses `tuning_micro` and `state_hash.h`
// quantizes: these numbers are compared for equality to decide a tie-break, and a
// tie-break is the last place in the project where an exactness argument should
// have to be made in a comment rather than read off the type.
using HalfPoints = int;

inline constexpr int HALF_POINTS_PER_POINT = 2;

inline constexpr HalfPoints half_points_of(int whole_points) {
	return whole_points * HALF_POINTS_PER_POINT;
}

// For display only. Nothing in this module or `standings.h` compares this.
inline constexpr double half_points_to_points(HalfPoints half) {
	return static_cast<double>(half) / static_cast<double>(HALF_POINTS_PER_POINT);
}

// --- part distance ------------------------------------------------------------
//
// G2 Art. 19, and the rule is explicit enough to encode verbatim: under 2 laps
// scores nothing, more than 2 laps but under 75% of the scheduled distance scores
// half, 75% or more scores full.
//
// It is why a race is a distance and not a lap count everywhere in this project:
// 75% of a scheduled distance is a number, and 75% of an authored lap count is a
// rounding argument.

// G2 Art. 19. Fewer than this many completed laps scores nothing at all.
inline constexpr int MIN_CLASSIFIED_LAPS = 2;

// G2 Art. 19. Below this fraction of the scheduled distance, half points.
inline constexpr double HALF_CREDIT_DISTANCE_FRACTION = 0.75;

enum class DistanceCredit : int {
	None = 0,
	Half = 1,
	Full = 2,
};

inline constexpr int DISTANCE_CREDIT_COUNT = 3;

inline const char *distance_credit_name(DistanceCredit credit) {
	switch (credit) {
		case DistanceCredit::None: return "none";
		case DistanceCredit::Half: return "half";
		case DistanceCredit::Full: return "full";
	}
	return "invalid";
}

// The credit a driver earned in one race.
//
// The lap test comes first and it is not redundant with the distance test: a
// driver who completes one lap of a three-lap race has covered 33% of the
// distance, which the fraction alone would score at half. G2 Art. 19 scores it at
// nothing, and the two-lap floor is what says so.
//
// A `scheduled_distance_m` of zero or less means "this session has no scheduled
// distance" — Practice and Qualifying Practice, per `scheduled_limit()`. Those
// award no championship points at all, so the fraction test is skipped rather
// than dividing by zero; the lap floor still applies.
inline DistanceCredit distance_credit(int laps_completed, double distance_m,
		double scheduled_distance_m) {
	if (laps_completed < MIN_CLASSIFIED_LAPS) {
		return DistanceCredit::None;
	}
	if (!(scheduled_distance_m > 0.0)) {
		return DistanceCredit::Full;
	}
	if (distance_m < HALF_CREDIT_DISTANCE_FRACTION * scheduled_distance_m) {
		return DistanceCredit::Half;
	}
	return DistanceCredit::Full;
}

// Whole points scaled by a credit, in half points. Exact integer arithmetic: an
// odd whole score at half credit keeps its half, which is the entire reason
// `HalfPoints` exists.
inline HalfPoints credited_half_points(int whole_points, DistanceCredit credit) {
	switch (credit) {
		case DistanceCredit::None: return 0;
		case DistanceCredit::Half: return whole_points;
		case DistanceCredit::Full: return half_points_of(whole_points);
	}
	return 0;
}

// --- a classification ---------------------------------------------------------

// One driver's result in one session. Everything the rules need and nothing else:
// no name, no nationality, no node. ADR-0044 keeps display text on the script
// side and ADR-0047 owns the roster; this is an id and some numbers.
struct DriverResult {
	int driver_id = DRIVER_NONE;

	// 1-based finishing position. **0 means not classified** — retired, black
	// flagged, or never started — and scores nothing on any scale. It is a value
	// rather than a separate flag so that every points lookup is one total
	// function of one integer.
	int position = 0;

	int laps_completed = 0;

	// Race distance actually covered, meters. Not derived from laps: a driver who
	// retires halfway round a lap has covered that half, and the part-distance
	// fraction is a distance test.
	double distance_m = 0.0;

	// Best lap of the session, seconds. **Zero or negative means no timed lap**,
	// which sorts behind every driver who set one. A kart that never crossed the
	// line has no lap, and 0.0 would otherwise be the fastest lap ever recorded.
	double best_lap_s = 0.0;

	bool has_lap() const { return best_lap_s > 0.0; }
};

// A list of driver ids and results, which per ADR-0043 is all a classification
// ever is or becomes.
struct Classification {
	SessionType type = SessionType::Practice;

	// What the session was scheduled to run, meters. Zero when the session is not
	// a distance. `of()` fills it from `session.h` so the compression in
	// `GAMEDESIGN.md` §4 has exactly one owner.
	double scheduled_distance_m = 0.0;

	int count = 0;
	DriverResult entries[RULES_MAX_ENTRIES] = {};

	// A classification of the right type, with the scheduled distance the
	// compressed weekend actually runs. Reads `scheduled_limit()` rather than
	// restating 3,750 m.
	static Classification of(SessionType type) {
		Classification result;
		result.type = type;
		const SessionLimit limit = scheduled_limit(type);
		result.scheduled_distance_m =
				(limit.kind == SessionLimitKind::Distance) ? limit.value : 0.0;
		return result;
	}

	// Returns false when full rather than overrunning. A caller that has more
	// entries than `RULES_MAX_ENTRIES` has parsed garbage, per that constant's
	// comment.
	bool add(const DriverResult &result) {
		if (count >= RULES_MAX_ENTRIES) {
			return false;
		}
		entries[count] = result;
		++count;
		return true;
	}

	int index_of(int driver_id) const {
		for (int i = 0; i < count; ++i) {
			if (entries[i].driver_id == driver_id) {
				return i;
			}
		}
		return -1;
	}

	const DriverResult *find(int driver_id) const {
		const int index = index_of(driver_id);
		return index < 0 ? nullptr : &entries[index];
	}

	// 1-based, or 0 for a driver who is not classified or not present. Both cases
	// score nothing, which is why they share a return value.
	int position_of(int driver_id) const {
		const DriverResult *result = find(driver_id);
		return result == nullptr ? 0 : result->position;
	}

	DistanceCredit credit_of(int driver_id) const {
		const DriverResult *result = find(driver_id);
		if (result == nullptr) {
			return DistanceCredit::None;
		}
		return distance_credit(result->laps_completed, result->distance_m,
				scheduled_distance_m);
	}
};

// --- an ordering --------------------------------------------------------------

// Drivers best-first. A grid and an intermediate classification are the same
// object seen from two sides — G2's intermediate classification after the heats
// *is* the Super Heat grid order, and it is also what Art. 19 awards championship
// points against — so one type serves both rather than two types being kept in
// step by hand.
struct Order {
	int count = 0;
	int driver_id[RULES_MAX_ENTRIES] = {};

	// 1-based. Slot 0 is pole, and first place.
	int position_of(int id) const {
		for (int i = 0; i < count; ++i) {
			if (driver_id[i] == id) {
				return i + 1;
			}
		}
		return 0;
	}

	// The driver in a 1-based position, or `DRIVER_NONE`.
	int at(int position) const {
		if (position < 1 || position > count) {
			return DRIVER_NONE;
		}
		return driver_id[position - 1];
	}

	bool add(int id) {
		if (count >= RULES_MAX_ENTRIES) {
			return false;
		}
		driver_id[count] = id;
		++count;
		return true;
	}
};

// --- position points, aggregated ----------------------------------------------

// A driver's total position points, which is the intermediate classification's
// raw material.
struct PointsTally {
	int count = 0;
	int driver_id[RULES_MAX_ENTRIES] = {};
	int points[RULES_MAX_ENTRIES] = {};

	int index_of(int id) const {
		for (int i = 0; i < count; ++i) {
			if (driver_id[i] == id) {
				return i;
			}
		}
		return -1;
	}

	int points_of(int id) const {
		const int index = index_of(id);
		return index < 0 ? 0 : points[index];
	}

	// Adds to an existing entry or creates one. Order of first appearance is
	// preserved, and that order is the last tie-break in `order_tally()`, so it
	// has to be stable.
	void add(int id, int scored) {
		const int index = index_of(id);
		if (index >= 0) {
			points[index] += scored;
			return;
		}
		if (count >= RULES_MAX_ENTRIES) {
			return;
		}
		driver_id[count] = id;
		points[count] = scored;
		++count;
	}
};

// Position points summed across every heat that was run. G2 Art. 18 C.
//
// **Written as a sum over `heat_count` heats even though `GAMEDESIGN.md` §4 runs
// exactly one.** The regulation's rule is an aggregation — the FIA runs three
// Qualifying Heats for Seniors and adds their position points to reach the
// intermediate classification — and the design's cut from three to one is a
// content decision, not a change to the arithmetic. Encoding the sum costs four
// lines and encoding the single-heat case would have to be unwritten the day
// somebody wants the real thing back.
inline PointsTally heat_position_tally(const Classification *heats, int heat_count) {
	PointsTally tally;
	if (heats == nullptr) {
		return tally;
	}
	for (int h = 0; h < heat_count; ++h) {
		const Classification &heat = heats[h];
		for (int i = 0; i < heat.count; ++i) {
			const DriverResult &result = heat.entries[i];
			tally.add(result.driver_id,
					points_for(PointsScale::HeatPosition, result.position));
		}
	}
	return tally;
}

// Position points from one Super Heat. G2 Art. 18 D. Orders the Final grid.
inline PointsTally super_heat_position_tally(const Classification &super_heat) {
	PointsTally tally;
	for (int i = 0; i < super_heat.count; ++i) {
		const DriverResult &result = super_heat.entries[i];
		tally.add(result.driver_id,
				points_for(PointsScale::SuperHeatPosition, result.position));
	}
	return tally;
}

// --- ties, and the one classification that breaks them ------------------------
//
// G2: ties break on the **Qualifying Practice classification, at every stage**.
// One rule for the whole weekend, which is why every ordering function below takes
// the qualifying classification as an argument rather than inventing a local rule.

// Qualifying position as a sort key: absent or unclassified sorts behind everyone
// who has a position. `position_of` returns 0 for both cases and 0 would otherwise
// sort ahead of pole.
inline int tie_break_key(const Classification &qualifying, int driver_id) {
	const int position = qualifying.position_of(driver_id);
	return position >= 1 ? position : RULES_MAX_ENTRIES + 1;
}

// A tally ordered into a classification: most points first, ties on the Qualifying
// Practice classification, and a final fall-back on order of first appearance.
//
// **The last fall-back is OURS and it only fires when the regulation has run out
// of answers** — two drivers on equal points who both failed to set a qualifying
// time. It exists because an ordering has to be total: a comparator that can call
// two distinct drivers equal makes the sort's output depend on the sort, and this
// project's determinism gates would then catch it as a divergence with no cause.
//
// Insertion sort, hand-rolled, on at most `RULES_MAX_ENTRIES` elements.
// `std::stable_sort` allocates, and this header does not.
inline Order order_tally(const PointsTally &tally, const Classification &qualifying) {
	int index[RULES_MAX_ENTRIES];
	for (int i = 0; i < tally.count; ++i) {
		index[i] = i;
	}
	for (int i = 1; i < tally.count; ++i) {
		const int current = index[i];
		int j = i - 1;
		while (j >= 0) {
			const int other = index[j];
			bool current_first = false;
			if (tally.points[current] != tally.points[other]) {
				current_first = tally.points[current] > tally.points[other];
			} else {
				const int current_key = tie_break_key(qualifying, tally.driver_id[current]);
				const int other_key = tie_break_key(qualifying, tally.driver_id[other]);
				if (current_key != other_key) {
					current_first = current_key < other_key;
				} else {
					current_first = current < other;
				}
			}
			if (!current_first) {
				break;
			}
			index[j + 1] = index[j];
			--j;
		}
		index[j + 1] = current;
	}

	Order order;
	for (int i = 0; i < tally.count; ++i) {
		order.add(tally.driver_id[index[i]]);
	}
	return order;
}

// --- the grid chain -----------------------------------------------------------
//
// `GAMEDESIGN.md` §4, and the whole reason the weekend has this shape:
//
//     Qualifying Practice   fastest lap        ->  Heat grid
//     Heat                  position points    ->  Super Heat grid
//     Super Heat            position points    ->  Final grid
//     Final                 championship points
//
// Each link is a separate function below, and each takes the qualifying
// classification because the tie-break never changes.

// Fill in `position` from the best lap of the session, fastest first. A driver
// with no timed lap is left unclassified at position 0 rather than being ranked
// behind the field: not setting a lap is not a slow lap.
//
// Equal lap times fall back on order of first appearance, marked OURS for the same
// reason `order_tally` needs a last resort. The regulation's real rule is who set
// the time first, and this project records no timestamp per lap; on a quantized
// simulated lap time an exact tie is reachable, so the case cannot be left open.
inline void assign_positions_by_best_lap(Classification &classification) {
	int index[RULES_MAX_ENTRIES];
	for (int i = 0; i < classification.count; ++i) {
		index[i] = i;
	}
	for (int i = 1; i < classification.count; ++i) {
		const int current = index[i];
		int j = i - 1;
		while (j >= 0) {
			const DriverResult &a = classification.entries[current];
			const DriverResult &b = classification.entries[index[j]];
			bool current_first = false;
			if (a.has_lap() != b.has_lap()) {
				current_first = a.has_lap();
			} else if (a.has_lap() && a.best_lap_s != b.best_lap_s) {
				current_first = a.best_lap_s < b.best_lap_s;
			} else {
				current_first = current < index[j];
			}
			if (!current_first) {
				break;
			}
			index[j + 1] = index[j];
			--j;
		}
		index[j + 1] = current;
	}

	int next_position = 1;
	for (int i = 0; i < classification.count; ++i) {
		DriverResult &result = classification.entries[index[i]];
		if (!result.has_lap()) {
			result.position = 0;
			continue;
		}
		result.position = next_position;
		++next_position;
	}
}

// The driver who set the fastest lap, or `DRIVER_NONE` if nobody set one.
// Order of first appearance breaks an exact tie, for the reason above.
inline int fastest_lap_driver(const Classification &classification) {
	int best = DRIVER_NONE;
	double best_time = 0.0;
	for (int i = 0; i < classification.count; ++i) {
		const DriverResult &result = classification.entries[i];
		if (!result.has_lap()) {
			continue;
		}
		if (best == DRIVER_NONE || result.best_lap_s < best_time) {
			best = result.driver_id;
			best_time = result.best_lap_s;
		}
	}
	return best;
}

// Link 1: the Heat grid is the Qualifying Practice classification.
//
// A driver with no timed lap is at the back, in order of first appearance. That is
// the one place in the chain where an unclassified driver still gets a grid slot,
// because a grid has to seat everybody who is entered.
inline Order heat_grid(const Classification &qualifying) {
	Order order;
	for (int position = 1; position <= qualifying.count; ++position) {
		for (int i = 0; i < qualifying.count; ++i) {
			if (qualifying.entries[i].position == position) {
				order.add(qualifying.entries[i].driver_id);
				break;
			}
		}
	}
	for (int i = 0; i < qualifying.count; ++i) {
		if (qualifying.entries[i].position == 0) {
			order.add(qualifying.entries[i].driver_id);
		}
	}
	return order;
}

// Link 2: the intermediate classification after the heats, which is both the
// Super Heat grid and what G2 Art. 19 awards its first championship points
// against. One function, because they are one ordering.
inline Order intermediate_classification(const Classification *heats, int heat_count,
		const Classification &qualifying) {
	return order_tally(heat_position_tally(heats, heat_count), qualifying);
}

// Link 3: the Final grid, from the Super Heat's position points.
inline Order final_grid(const Classification &super_heat, const Classification &qualifying) {
	return order_tally(super_heat_position_tally(super_heat), qualifying);
}

// --- championship points for one round ----------------------------------------
//
// **Three classifications per round, not the Final alone**, and here is exactly
// which three and why. G2 Art. 19, as recorded in `docs/REFERENCES.md`: "the
// intermediate classification after the heats, the Super Heat classification, and
// the Final."
//
//   1. the **intermediate classification** after the heats  -> 25, 22, 19, ...
//   2. the **Super Heat** classification                    -> 25, 22, 19, ...
//   3. the **Final**                                        -> 50, 44, 38, ...
//   plus one point for the fastest lap of the Final.
//
// Two readings of `GAMEDESIGN.md` §4 had to be settled to get that list, and both
// are worth stating because the wrong one is plausible:
//
// **It is not one award per heat.** §4's table row reads "Championship, heats +
// Super Heat classifications", which invites summing the 25-scale once for each
// heat run. It is not: the heats produce **one** classification between them — the
// intermediate one, built by summing their *position* points — and that single
// classification scores once. This is what keeps "three classifications per round"
// true whether a round runs one heat or the FIA's three, and it is why the cut
// from three heats to one does not change any championship total.
//
// **The Super Heat is scored twice, on two different scales, and that is correct.**
// Its position points (90, 80, 72, ...) order the Final grid under Art. 18 D; its
// classification separately awards championship points (25, 22, 19, ...) under
// Art. 19. Two scales, one classification. This is precisely the collapse
// ADR-0043 warns about, seen from the inside: an implementation that used one
// array for both would produce a plausible table and a wrong championship.
//
// Part-distance scaling (G2 Art. 19) applies to each of the three.

// One round's championship award for one driver, in half points.
struct RoundAward {
	int driver_id = DRIVER_NONE;

	HalfPoints intermediate = 0;
	HalfPoints super_heat = 0;
	HalfPoints final_race = 0;
	HalfPoints fastest_lap = 0;

	// The Final finishing position, 1-based, 0 if not classified. Carried because
	// `standings.h` cannot recover it from the points: see the note on
	// `CHAMPIONSHIP_FINAL_POINTS` — a half-credit Final award is numerically
	// identical to a full-credit heat award, so the map from points back to
	// position is not injective.
	int final_position = 0;

	HalfPoints total() const {
		return intermediate + super_heat + final_race + fastest_lap;
	}
};

// Everything a round produced, per driver, plus the two orderings a caller wants
// to show.
struct RoundScore {
	int count = 0;
	RoundAward awards[RULES_MAX_ENTRIES] = {};

	// The intermediate classification after the heats. Also the Super Heat grid.
	Order intermediate;

	// The Final grid, from the Super Heat's position points.
	Order final_grid;

	int fastest_lap_driver_id = DRIVER_NONE;

	int index_of(int driver_id) const {
		for (int i = 0; i < count; ++i) {
			if (awards[i].driver_id == driver_id) {
				return i;
			}
		}
		return -1;
	}

	const RoundAward *find(int driver_id) const {
		const int index = index_of(driver_id);
		return index < 0 ? nullptr : &awards[index];
	}

	HalfPoints total_of(int driver_id) const {
		const RoundAward *award = find(driver_id);
		return award == nullptr ? 0 : award->total();
	}
};

// The part-distance credit for the intermediate classification, aggregated across
// every heat a driver ran.
//
// **The aggregation is OURS.** G2 Art. 19's rule is written for one race, and the
// intermediate classification is not a race — it is a sum over the heats. Summing
// laps and distance across the heats and testing the totals is the reading taken
// here, because it reduces exactly to the single-race rule when a round runs one
// heat, which is the only case `GAMEDESIGN.md` §4 currently runs. The alternative
// readings — take the worst credit of any heat, or credit each heat separately —
// both differ from this one only in a three-heat round that the design does not
// have, and neither is more obviously the regulation's intent.
inline DistanceCredit heats_credit(const Classification *heats, int heat_count,
		int driver_id) {
	if (heats == nullptr || heat_count <= 0) {
		return DistanceCredit::None;
	}
	int laps = 0;
	double distance = 0.0;
	double scheduled = 0.0;
	bool present = false;
	for (int h = 0; h < heat_count; ++h) {
		scheduled += heats[h].scheduled_distance_m;
		const DriverResult *result = heats[h].find(driver_id);
		if (result == nullptr) {
			continue;
		}
		present = true;
		laps += result->laps_completed;
		distance += result->distance_m;
	}
	if (!present) {
		return DistanceCredit::None;
	}
	return distance_credit(laps, distance, scheduled);
}

// Score one round. Pure: it reads four classifications and returns numbers.
//
// The entry list is taken from the Final's classification, extended by anybody who
// appears in an earlier session and not in it — a driver who scored in the heats
// and then failed to start the Final keeps what he scored, which is the whole
// point of championship points coming from three classifications rather than one.
inline RoundScore score_round(const Classification &qualifying,
		const Classification *heats, int heat_count,
		const Classification &super_heat,
		const Classification &final_race) {
	RoundScore score;
	score.intermediate = intermediate_classification(heats, heat_count, qualifying);
	score.final_grid = final_grid(super_heat, qualifying);
	score.fastest_lap_driver_id = fastest_lap_driver(final_race);

	// Collect the round's drivers, Final first so the common case is in finishing
	// order, then anyone who only appears earlier.
	int ids[RULES_MAX_ENTRIES];
	int id_count = 0;
	const Classification *sources[3] = { &final_race, &super_heat, &qualifying };
	for (int s = 0; s < 3; ++s) {
		for (int i = 0; i < sources[s]->count && id_count < RULES_MAX_ENTRIES; ++i) {
			const int id = sources[s]->entries[i].driver_id;
			bool seen = false;
			for (int k = 0; k < id_count; ++k) {
				seen = seen || ids[k] == id;
			}
			if (!seen) {
				ids[id_count] = id;
				++id_count;
			}
		}
	}
	for (int h = 0; h < heat_count && heats != nullptr; ++h) {
		for (int i = 0; i < heats[h].count && id_count < RULES_MAX_ENTRIES; ++i) {
			const int id = heats[h].entries[i].driver_id;
			bool seen = false;
			for (int k = 0; k < id_count; ++k) {
				seen = seen || ids[k] == id;
			}
			if (!seen) {
				ids[id_count] = id;
				++id_count;
			}
		}
	}

	for (int i = 0; i < id_count; ++i) {
		const int id = ids[i];
		RoundAward award;
		award.driver_id = id;

		// 1. the intermediate classification after the heats
		award.intermediate = credited_half_points(
				points_for(PointsScale::ChampionshipHeat, score.intermediate.position_of(id)),
				heats_credit(heats, heat_count, id));

		// 2. the Super Heat classification
		award.super_heat = credited_half_points(
				points_for(PointsScale::ChampionshipHeat, super_heat.position_of(id)),
				super_heat.credit_of(id));

		// 3. the Final
		award.final_position = final_race.position_of(id);
		award.final_race = credited_half_points(
				points_for(PointsScale::ChampionshipFinal, award.final_position),
				final_race.credit_of(id));

		// Plus the fastest lap of the Final. **Not scaled by part distance**, and
		// that is a reading rather than a quotation: Art. 19 attaches the point to a
		// lap, and the part-distance rule scales the points awarded for a
		// classification. So a driver who set the fastest lap and then retired on
		// lap 3 keeps the point and scores nothing for the classification. The
		// opposite reading is defensible; this one is written down.
		award.fastest_lap = (id == score.fastest_lap_driver_id)
				? half_points_of(FINAL_FASTEST_LAP_POINT)
				: 0;

		score.awards[score.count] = award;
		++score.count;
	}
	return score;
}

// --- sequencing ---------------------------------------------------------------
//
// Which session runs next, and whether the round is over. ADR-0043: a pure state
// machine, no engine, no scene, no setting. It is here rather than in GDScript
// because "what runs after the Super Heat" is a fact about the regulations, and a
// front end that owned it would be a second owner of the weekend's shape.

// G2 Art. 18's order, verbatim: "Free Practice, Qualifying Practice, Qualifying
// Heats, Super Heat(s) and a final phase."
inline constexpr SessionType ROUND_ORDER[] = {
	SessionType::Practice,
	SessionType::Qualifying,
	SessionType::Heat,
	SessionType::SuperHeat,
	SessionType::Final,
};

// Derived rather than written, so adding a session to the order above cannot leave
// the count behind. `test_race_rules.cpp` separately asserts it equals
// `SESSION_TYPE_COUNT`, which is what says the round contains every session type
// there is.
inline constexpr int ROUND_ORDER_COUNT =
		static_cast<int>(sizeof(ROUND_ORDER) / sizeof(ROUND_ORDER[0]));

inline constexpr SessionType first_session_of_round() {
	return ROUND_ORDER[0];
}

inline constexpr SessionType last_session_of_round() {
	return ROUND_ORDER[ROUND_ORDER_COUNT - 1];
}

// Where a session sits in the round, or -1 for a type that is not in it. Every
// `SessionType` is currently in the round, and the -1 is kept because the switch
// in `session.h` can grow a value before this array does.
inline int round_order_index(SessionType type) {
	for (int i = 0; i < ROUND_ORDER_COUNT; ++i) {
		if (ROUND_ORDER[i] == type) {
			return i;
		}
	}
	return -1;
}

// The session after this one, or false when the round is complete.
inline bool next_session_of_round(SessionType current, SessionType &out) {
	const int index = round_order_index(current);
	if (index < 0 || index + 1 >= ROUND_ORDER_COUNT) {
		return false;
	}
	out = ROUND_ORDER[index + 1];
	return true;
}

// A round is complete when its Final has run. Practice is in the order and is
// skippable; the Final is what ends the round.
inline bool round_complete_after(SessionType completed) {
	return completed == last_session_of_round();
}

// Whether a session's classification feeds `score_round`. Qualifying Practice sets
// the Heat grid and breaks every tie in the weekend and awards **nothing**, which
// is a distinction worth having a function for.
inline bool session_awards_championship_points(SessionType type) {
	switch (type) {
		case SessionType::Practice: return false;
		case SessionType::Qualifying: return false;
		case SessionType::Heat: return true;
		case SessionType::SuperHeat: return true;
		case SessionType::Final: return true;
	}
	return false;
}

// Whether a session's result forms the next session's grid. Everything but the
// Final, which forms the championship instead — that is the grid chain read as a
// predicate, and `test_race_rules.cpp` checks the two agree.
inline bool session_sets_next_grid(SessionType type) {
	switch (type) {
		case SessionType::Practice: return false;
		case SessionType::Qualifying: return true;
		case SessionType::Heat: return true;
		case SessionType::SuperHeat: return true;
		case SessionType::Final: return false;
	}
	return false;
}

// The lap count a distance actually produces on a circuit. G2 Art. 18 and G4
// Art. 6: "the minimum number of full laps necessary for reaching the distance",
// which is a ceiling and not a rounding.
//
// Nothing in the rules needs this — part distance is measured in meters — but the
// front end has to print a lap count, and a second implementation of a ceiling is
// how a HUD ends up one lap out from the flag.
inline int scheduled_laps(double scheduled_distance_m, double lap_length_m) {
	if (!(scheduled_distance_m > 0.0) || !(lap_length_m > 0.0)) {
		return 0;
	}
	return static_cast<int>(std::ceil(scheduled_distance_m / lap_length_m));
}

} // namespace kart::core

#endif // KART_CORE_RACE_RULES_H
